# SPDX-License-Identifier: Apache-2.0
"""Seed prompts for self-generated NVFP4 calibration (our own text; no external
dataset, nothing leaves the cluster). A .py module so the wheel always ships it."""

PROMPTS = [
    "Explain how a hash map handles collisions, with a short example.",
    "Summarize the causes of the French Revolution in five bullet points.",
    "What are the trade-offs between microservices and a monolith?",
    "Give me a weekly training plan for a beginner runner.",
    "Why is the sky blue? Explain at a high-school level.",
    "Compare TCP and UDP and when you would use each.",
    "Write a polite email declining a meeting invitation.",
    "What is the difference between precision and recall?",
    "Explain the CAP theorem with a concrete distributed database example.",
    "Draft a product description for a waterproof hiking backpack.",
    "How does photosynthesis convert light into chemical energy?",
    "List common logical fallacies and give one example of each.",
    "Explain inflation and how central banks try to control it.",
    "Describe the plot structure of a classic hero's journey.",
    "What should I consider when choosing a database for time-series data?",
    "Explain gradient descent and the role of the learning rate.",
    "Write a Python function that merges overlapping intervals and explain its complexity.",
    "Implement a thread-safe LRU cache in Rust.",
    "Write a SQL query that returns the top 3 customers by revenue per month.",
    "Refactor this JavaScript callback code to async/await: fs.readFile(p, (e, d) => { if (e) throw e; console.log(d); });",
    "Write a bash script that finds the 10 largest files under a directory.",
    "Explain what this regex does: ^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,}$",
    "Write a C function that reverses a singly linked list in place.",
    "Implement binary search in Go and write two unit tests for it.",
    "Explain the difference between a process and a thread with examples in Python.",
    "Write a Dockerfile for a small Flask application with a non-root user.",
    "Write a TypeScript type for a deeply readonly object.",
    "Explain CUDA warps, shared memory, and coalesced memory access.",
    "Write a Kubernetes Deployment manifest with a readiness probe for an HTTP service.",
    "Implement quicksort in Haskell and explain the recursion.",
    "Write a Python asyncio program that fetches 5 URLs concurrently with a timeout.",
    "Explain how a B-tree index speeds up database lookups.",
    "Solve step by step: a train travels 120 km in 1.5 hours; what is its average speed in m/s?",
    "Prove that the square root of 2 is irrational.",
    "Compute the derivative of x^3 * sin(x) and explain each rule used.",
    "What is the probability of rolling at least one six in four rolls of a die?",
    "Explain eigenvalues and eigenvectors with a 2x2 matrix example.",
    "Solve the system: 2x + 3y = 7 and x - y = 1.",
    "Explain Bayes' theorem with a medical test example.",
    "Integrate 1/(1+x^2) from 0 to 1 and explain the result.",
    "Erkläre in einfachen Worten, wie ein Elektromotor funktioniert.",
    "Schreibe eine kurze Zusammenfassung über die Vor- und Nachteile von Homeoffice.",
    "Explique la différence entre le climat et la météo.",
    "Escribe un poema corto sobre el mar al amanecer.",
    "Spiega come funziona la fotosintesi in poche frasi.",
    "Leg uit wat een blockchain is aan een tienjarige.",
    "请用简单的语言解释什么是机器学习。",
    "日本の四季について短い文章を書いてください。",
    "Объясни, почему важно регулярно делать резервные копии данных.",
    "Explique em português o que é inflação.",
    "Return a JSON object describing three fictional employees with name, role, and skills.",
    "Create a markdown table comparing Python, Rust, and Go on speed, safety, and ecosystem.",
    "Write a step-by-step incident postmortem template for a web service outage.",
    "Given the log line '2026-09-25 ERROR db timeout after 30s', suggest likely causes and next steps.",
    "Write a function-calling style plan to book a flight, listing each tool call and its arguments.",
    "Summarize the following text in two sentences: The quick adoption of renewable energy has changed grid operations, requiring storage, forecasting, and flexible demand to balance variable supply.",
    "Write a short story (about 200 words) about a lighthouse keeper who finds a message in a bottle.",
    "Outline a 30-minute talk on data privacy for software engineers.",
    "Translate to German and explain any idioms: 'It's raining cats and dogs, so let's call it a day.'",
    "Act as a code reviewer and list issues in: def add(a, b): return a+b if type(a)==int else None",
    "Explain the attention mechanism in transformers, including queries, keys, and values.",
    "Describe how speculative decoding speeds up language model inference.",
    "What are the main differences between FP8, FP4 and bfloat16 number formats?",
    "Plan a three-day trip to Kyoto with a daily itinerary.",
]
